/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scalability;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.concurrent.ThreadLocalRandom;

class JettyServerTest {
    @Test
    void verifyServer() throws Exception {
        var port = ThreadLocalRandom.current().nextInt(10000, 60000);
        var server = JettyServer.setupServer(port);
        assertNotNull(server, "server should not be null");
        server.start();
        server.stop();
    }
}
