/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package scalability;

public class App {

    public static void main(String[] args) throws Exception {
        System.out.print("Starting application on 8080...");

        final var server = JettyServer.setupServer(8081);

        // Add our simple handler
        server.setHandler(new SimpleHandler());

        server.start();

        System.out.println("started!");
        server.join();

        System.out.println("See you next time!");
    }
}
